(() => {
  'use strict';
  const KEY='stoicky-kompas-data-v1';
  const INTERESTS=[
    {id:'nature',name:'Příroda',kind:'Na vzduch',title:'Dej si procházku venku',step:'Vyber místo a připrav si boty.',low:true},
    {id:'reading',name:'Čtení',kind:'Klid',title:'Přečti si pár stránek',step:'Polož knihu tam, kde ji zítra uvidíš.',low:true},
    {id:'friends',name:'Kamarádi',kind:'Lidé',title:'Ozvi se někomu blízkému',step:'Pošli jednu zprávu bez složitého plánování.',low:true},
    {id:'sport',name:'Pohyb',kind:'Pohyb',title:'Dopřej si pohyb podle energie',step:'Zvol si krátký čas, třeba 20 minut.',low:false},
    {id:'creative',name:'Tvoření',kind:'Nápad',title:'Věnuj chvíli vlastnímu projektu',step:'Otevři rozdělanou věc na 15 minut.',low:false},
    {id:'rest',name:'Odpočinek',kind:'Zvolni',title:'Naplánuj si opravdový odpočinek',step:'Dej telefon stranou a vyber si jednu příjemnou věc.',low:true}
  ];
  const WORDS={nature:/přírod|procház|venku|výlet|\bles\b/i,reading:/čt|knih/i,friends:/kamarád|přátel|kulečník|setkán/i,sport:/běh|běž|cvič|fitk|sport/i,creative:/tvoř|projekt|kresl|psaní/i,rest:/odpoč|spán|klid/i};
  const $=id=>document.getElementById(id);
  const escDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const today=()=>escDate(new Date());
  const weekStart=(date=new Date())=>{const d=new Date(date.getFullYear(),date.getMonth(),date.getDate());d.setDate(d.getDate()-((d.getDay()+6)%7));return escDate(d)};
  const dateFromISO=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)};
  const dateLabel=s=>dateFromISO(s).toLocaleDateString('cs-CZ',{day:'numeric',month:'long',year:'numeric'});
  const weekLabel=s=>{const d=dateFromISO(s),end=new Date(d);end.setDate(d.getDate()+6);return `${d.toLocaleDateString('cs-CZ',{day:'numeric',month:'numeric'})}–${end.toLocaleDateString('cs-CZ',{day:'numeric',month:'numeric',year:'numeric'})}`};
  const validDate=s=>/^\d{4}-\d{2}-\d{2}$/.test(s)&&escDate(dateFromISO(s))===s;
  const cleanText=s=>String(s||'').slice(0,5000);
  const fresh=()=>({version:1,entries:{},goals:[],checks:{},reflections:{},interests:['nature','reading','friends','sport','rest'],suggestions:{}});
  function normalize(raw){
    if(!raw||raw.version!==1||typeof raw!=='object')throw Error('Neznámý formát zálohy.');
    const data=fresh();
    for(const [date,e] of Object.entries(raw.entries||{}))if(validDate(date)&&e&&typeof e==='object')data.entries[date]={good:cleanText(e.good),learned:cleanText(e.learned),note:cleanText(e.note),activities:Array.isArray(e.activities)?e.activities.filter(id=>INTERESTS.some(x=>x.id===id)).slice(0,6):[]};
    data.goals=(Array.isArray(raw.goals)?raw.goals:[]).slice(0,100).filter(g=>g&&typeof g.name==='string'&&Number.isInteger(g.target)&&g.target>=1&&g.target<=14&&typeof g.id==='string').map(g=>({id:g.id.slice(0,80),name:g.name.slice(0,70),target:g.target}));
    for(const [id,days] of Object.entries(raw.checks||{}))if(Array.isArray(days))data.checks[id.slice(0,80)]=[...new Set(days.filter(validDate))].slice(0,3000);
    for(const [date,r] of Object.entries(raw.reflections||{}))if(validDate(date)&&r&&typeof r==='object')data.reflections[date]={good:cleanText(r.good),control:cleanText(r.control),next:cleanText(r.next)};
    if(Array.isArray(raw.interests))data.interests=raw.interests.filter(id=>INTERESTS.some(x=>x.id===id));
    if(raw.suggestions&&typeof raw.suggestions==='object'){for(const [id,date] of Object.entries(raw.suggestions))if(INTERESTS.some(x=>x.id===id)&&validDate(date))data.suggestions[id]=date}
    return data;
  }
  let data;try{data=normalize(JSON.parse(localStorage.getItem(KEY)))}catch{data=fresh()}
  const status=message=>{$('status').textContent=message;clearTimeout(status.timer);status.timer=setTimeout(()=>$('status').textContent='',6000)};
  const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(data));return true}catch{status('Uložení se nepovedlo. Stáhni si zálohu a zkontroluj volné místo v prohlížeči.');return false}};
  const node=(tag,cls,content)=>{const el=document.createElement(tag);if(cls)el.className=cls;if(content!=null)el.textContent=content;return el};
  const blank=(container,message)=>container.append(node('p','muted',message));
  function showView(id){document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.id===id));document.querySelectorAll('[data-view]').forEach(el=>{el.classList.toggle('active',el.dataset.view===id);if(el.dataset.view===id)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current')});window.scrollTo({top:0,behavior:'smooth'})}
  document.querySelectorAll('[data-view],[data-jump]').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.view||btn.dataset.jump)));
  $('today-date').textContent=new Date().toLocaleDateString('cs-CZ',{weekday:'long',day:'numeric',month:'long'});
  $('entry-date').value=today();$('entry-date').max=today();
  function renderActivityInputs(){const holder=$('activity-inputs');holder.replaceChildren();for(const interest of INTERESTS){const label=node('label','activity-choice'),box=node('input');box.type='checkbox';box.value=interest.id;box.name='activity';label.append(box,document.createTextNode(` ${interest.name}`));holder.append(label)}}
  renderActivityInputs();
  function loadEntry(){const e=data.entries[$('entry-date').value]||{};$('entry-good').value=e.good||'';$('entry-learned').value=e.learned||'';$('entry-note').value=e.note||'';document.querySelectorAll('input[name=activity]').forEach(box=>box.checked=(e.activities||[]).includes(box.value))}
  $('entry-date').addEventListener('change',loadEntry);
  $('journal-form').addEventListener('submit',event=>{event.preventDefault();const date=$('entry-date').value;if(!validDate(date)||date>today())return status('Vyber dnešní nebo dřívější den.');const entry={good:$('entry-good').value.trim(),learned:$('entry-learned').value.trim(),note:$('entry-note').value.trim(),activities:[...document.querySelectorAll('input[name=activity]:checked')].map(box=>box.value)};if(!entry.good&&!entry.learned&&!entry.note&&!entry.activities.length)return status('Napiš myšlenku nebo označ aktivitu.');data.entries[date]=entry;if(save()){status('Zápis uložen.');render()}});
  function renderEntries(){const container=$('entry-list');container.replaceChildren();const dates=Object.keys(data.entries).sort().reverse();if(!dates.length)return blank(container,'Zatím žádný zápis. Začni třeba jednou větou.');for(const date of dates.slice(0,25)){const item=node('article','entry');item.append(node('h4','',dateLabel(date)));const e=data.entries[date];for(const [label,key] of [['Povedlo se','good'],['Naučil ses','learned'],['Poznámka','note']])if(e[key])item.append(node('p','',`${label}: ${e[key]}`));if(e.activities?.length)item.append(node('small','',`Aktivity: ${e.activities.map(id=>INTERESTS.find(x=>x.id===id)?.name).filter(Boolean).join(', ')}`));const btn=node('button','small-button','Upravit');btn.type='button';btn.addEventListener('click',()=>{$('entry-date').value=date;loadEntry();showView('journal')});item.append(btn);container.append(item)}if(dates.length>25)blank(container,`Zobrazeno posledních 25 z ${dates.length} zápisů; všechny jsou v záloze.`)}
  $('goal-form').addEventListener('submit',event=>{event.preventDefault();const name=$('goal-name').value.trim(),target=Number($('goal-target').value);if(!name||!Number.isInteger(target)||target<1||target>14)return status('Zadej název a počet 1 až 14.');data.goals.push({id:crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`,name:name.slice(0,70),target});if(save()){$('goal-form').reset();$('goal-target').value=3;render()}});
  function countWeek(id){const start=weekStart();return (data.checks[id]||[]).filter(d=>weekStart(dateFromISO(d))===start).length}
  function renderGoals(){const container=$('goal-list'),home=$('home-goals');container.replaceChildren();home.replaceChildren();$('week-label').textContent=weekLabel(weekStart());if(!data.goals.length){blank(container,'Přidej první týdenní cíl. Třeba jednu procházku.');blank(home,'Zatím žádné cíle. Vlastní tempo si zvolíš ty.');return}for(const goal of data.goals){const count=countWeek(goal.id),box=node('article','goal-card'),head=node('div','goal-head');head.append(node('strong','',goal.name),node('span','goal-meta',`${count} / ${goal.target} tento týden`));box.append(head);const progress=node('div','progress'),bar=node('span');bar.style.width=`${Math.min(100,100*count/goal.target)}%`;progress.append(bar);box.append(progress);const actions=node('div','goal-actions');const dayLabel=node('label','date-choice','Den: '),day=node('input');day.type='date';day.value=today();day.min=weekStart();day.max=today();day.setAttribute('aria-label',`Den pro cíl ${goal.name}`);dayLabel.append(day);actions.append(dayLabel);const add=node('button','small-button','+ Zapsat den');add.type='button';add.addEventListener('click',()=>{const date=day.value;if(!validDate(date)||date<weekStart()||date>today())return status('Vyber den v tomto týdnu.');if((data.checks[goal.id]||[]).includes(date))return status('Tenhle den už máš zapsaný.');data.checks[goal.id]=[...(data.checks[goal.id]||[]),date];if(save())render()});actions.append(add);const undo=node('button','small-button','Vrátit zvolený den');undo.type='button';undo.addEventListener('click',()=>{const date=day.value;if(!(data.checks[goal.id]||[]).includes(date))return status('Pro vybraný den není co vracet.');data.checks[goal.id]=data.checks[goal.id].filter(d=>d!==date);if(save())render()});actions.append(undo);const remove=node('button','small-button danger','Smazat cíl');remove.type='button';remove.addEventListener('click',()=>{if(!confirm(`Smazat cíl „${goal.name}“ i jeho záznamy?`))return;data.goals=data.goals.filter(g=>g.id!==goal.id);delete data.checks[goal.id];if(save())render()});actions.append(remove);box.append(actions);container.append(box);home.append(node('div','mini',`${goal.name} · ${count} z ${goal.target}`))}}
  function renderInterests(){const list=$('interest-list');list.replaceChildren();for(const interest of INTERESTS){const btn=node('button',`interest ${data.interests.includes(interest.id)?'selected':''}`,interest.name);btn.type='button';btn.setAttribute('aria-pressed',data.interests.includes(interest.id)?'true':'false');btn.addEventListener('click',()=>{data.interests=data.interests.includes(interest.id)?data.interests.filter(id=>id!==interest.id):[...data.interests,interest.id];if(save())renderInterests()});list.append(btn)}}
  let currentSuggestion=null,seen=[];
  const dayNumber=date=>{const [y,m,d]=date.split('-').map(Number);return Math.floor(Date.UTC(y,m-1,d)/86400000)};
  const daysSince=date=>dayNumber(today())-dayNumber(date);
  function relevantDates(interest){const dates=new Set();for(const [date,e] of Object.entries(data.entries)){const text=[e.good,e.learned,e.note].join(' ');if(e.activities?.includes(interest.id)||WORDS[interest.id].test(text))dates.add(date)}for(const goal of data.goals)if(WORDS[interest.id].test(goal.name))for(const date of data.checks[goal.id]||[])dates.add(date);return [...dates].filter(date=>date<=today()).sort().reverse()}
  function renderBalance(){const holder=$('balance-list');holder.replaceChildren();const logged=Object.keys(data.entries).filter(date=>date<=today()&&daysSince(date)<30).length;if(!logged)return blank(holder,'Zatím není z čeho vycházet. Začni pár zápisy nebo označ aktivitu v deníku.');for(const interest of INTERESTS){const count=relevantDates(interest).filter(date=>daysSince(date)<30).length;const row=node('div','balance-row');row.append(node('strong','',interest.name),node('span','muted',count?`${count} ${count===1?'den':'dní'} v záznamech`:'Bez zmínky v záznamech'));holder.append(row)}holder.append(node('small','muted',`Zapsaných dní v období: ${logged}. Přehled měří jen záznamy, nikoli celý tvůj život.`))}
  function suggestion(){let pool=INTERESTS.filter(x=>data.interests.includes(x.id));if(!pool.length)pool=INTERESTS.filter(x=>x.id==='rest');const energy=document.querySelector('input[name=energy]:checked')?.value||'medium';const history=Object.keys(data.entries).filter(date=>date<=today()&&daysSince(date)<30).length;const ranked=pool.map(x=>{const last=relevantDates(x)[0],recent=data.suggestions[x.id],score=(last?Math.min(32,daysSince(last)):history>=4?32:10)+(energy==='low'?(x.low?12:-12):energy==='high'?(x.low?0:5):0)+(recent&&daysSince(recent)<7?-18:0);return {...x,last,score}}).sort((a,b)=>b.score-a.score);let pick=ranked.find(x=>!seen.includes(x.id));if(!pick){seen=[];pick=ranked[0]}seen.push(pick.id);currentSuggestion=pick;$('suggestion-kind').textContent=pick.kind;$('suggestion-title').textContent=pick.title;const gap=pick.last?daysSince(pick.last):null;$('suggestion-reason').textContent=gap!=null&&gap>=14?`Oblast „${pick.name.toLowerCase()}“ se v záznamech ${gap} dní neobjevila. Pokud máš chuť, můžeš se k ní vrátit.`:gap==null&&history>=4?`Oblast „${pick.name.toLowerCase()}“ se v zápiscích za posledních 30 dní neobjevila. To neznamená, že ses jí nevěnoval; třeba je to jen dobrý tip.`:'Návrh podle toho, co tě zajímá a kolik máš dnes energie. Klidně si vyber jinak.';$('suggestion-step').textContent=`První krok: ${pick.step}`;$('suggestion-feedback').textContent='';$('suggestion-card').hidden=false}
  $('suggest-button').addEventListener('click',suggestion);$('another-suggestion').addEventListener('click',suggestion);$('accept-suggestion').addEventListener('click',()=>{if(!currentSuggestion)return;data.suggestions[currentSuggestion.id]=today();if(save())$('suggestion-feedback').textContent='Fajn. Je to možnost, ne povinnost. Kdykoli se můžeš rozhodnout jinak.'});
  function renderThought(){const items=window.STOIC_THOUGHTS||[];if(!items.length)return;const thought=items[((dayNumber(today())%items.length)+items.length)%items.length],section=Number(thought.section.match(/\d+/)?.[0]);$('thought-source').textContent=thought.type==='stoic'?`Epiktétos, Enchiridion ${thought.section}`:'Cvičení všímavosti';$('thought-count').textContent=thought.type==='stoic'&&window.FAVORITE_SECTIONS.includes(section)?'★ Tvoje vybraná kapitola':thought.type==='stoic'?'Stoická inspirace':'Inspirace všímavostí';$('thought-title').textContent=thought.title;$('thought-text').textContent=thought.thought;$('thought-question').textContent=thought.question;$('thought-step').textContent=`Malý pokus: ${thought.step}`;$('thought-note').textContent=thought.type==='stoic'?'Autorská česká parafráze, nikoli doslovný citát.':'Nenáboženské cvičení inspirované všímavostí, nikoli historický citát.'}
  $('thought-archive').addEventListener('toggle',()=>{const holder=$('thought-library');if(!$('thought-archive').open||holder.children.length)return;for(const card of window.STOIC_LIBRARY||[]){const section=Number(card.section.match(/\d+/)?.[0]),favorite=card.type==='stoic'&&window.FAVORITE_SECTIONS.includes(section),item=node('article','thought-item');item.append(node('small','kicker',card.type==='stoic'?`ENCHIRIDION ${card.section}${favorite?' · ★ TVŮJ VÝBĚR':''}`:'VŠÍMAVOST'),node('h3','',card.title),node('p','',card.thought),node('p','muted',`Otázka: ${card.question}`),node('p','muted',`Krok: ${card.step}`));holder.append(item)}});
  function renderHomePrompt(){const day=new Date().getDay(),history=Object.keys(data.entries).filter(date=>date<=today()&&daysSince(date)<30).length,lastFriends=relevantDates(INTERESTS.find(x=>x.id==='friends'))[0],friendGap=lastFriends?daysSince(lastFriends):null;if(data.interests.includes('friends')&&history>=4&&(friendGap==null||friendGap>=21)){$('home-prompt-title').textContent='Co vztahy v poslední době?';$('home-prompt').textContent='V zápiscích za poslední týdny je málo zmínek o setkání s blízkými. Možná by ti udělalo dobře se někomu ozvat; tvoje záznamy ale nemusí zachycovat všechno.'}else{$('home-prompt-title').textContent=day===5||day===6?'Co by ti udělalo dobře o víkendu?':'Jakou jednu věc dnes ovlivníš?';$('home-prompt').textContent=day===5||day===6?'Kompas ti nabídne pár nápadů podle tvých zájmů a energie. Odpočinek je taky dobrý plán.':'Nemusíš dnes zvládnout všechno. Jeden dobrý krok úplně stačí.'}}
  function loadReflection(){const r=data.reflections[weekStart()]||{};$('reflection-week').textContent=`Týden ${weekLabel(weekStart())}`;$('reflect-good').value=r.good||'';$('reflect-control').value=r.control||'';$('reflect-next').value=r.next||''}
  $('reflection-form').addEventListener('submit',event=>{event.preventDefault();const r={good:$('reflect-good').value.trim(),control:$('reflect-control').value.trim(),next:$('reflect-next').value.trim()};if(!Object.values(r).some(Boolean))return status('Stačí jedna věta, ale napiš ji před uložením.');data.reflections[weekStart()]=r;if(save()){status('Ohlédnutí uloženo.');renderReflections()}});
  function renderReflections(){const container=$('reflection-list');container.replaceChildren();const weeks=Object.keys(data.reflections).sort().reverse();if(!weeks.length)return blank(container,'Zatím žádné ohlédnutí. Můžeš začít klidně uprostřed týdne.');for(const week of weeks.slice(0,15)){const r=data.reflections[week],item=node('article','reflection-item');item.append(node('h4','',weekLabel(week)));for(const [label,key] of [['Povedlo se','good'],['V mých silách','control'],['Další krok','next']])if(r[key])item.append(node('p','',`${label}: ${r[key]}`));container.append(item)}}
  function render(){renderEntries();renderGoals();renderInterests();renderReflections();renderBalance();renderThought();renderHomePrompt()}
  $('export-button').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`stoicky-kompas-zaloha-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Záloha se stahuje.')});
  $('import-file').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;try{if(file.size>5_000_000)throw Error('Soubor je příliš velký.');const next=normalize(JSON.parse(await file.text()));if(!confirm('Načtení zálohy nahradí současné záznamy v tomto prohlížeči. Pokračovat?'))return;data=next;if(save()){loadEntry();loadReflection();render();status('Záloha načtena.')}}catch(err){status(`Zálohu se nepovedlo načíst: ${err.message}`)}finally{event.target.value=''}});
  loadEntry();loadReflection();render();
  if('serviceWorker'in navigator&&location.protocol!=='file:')window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();
