(() => {
  'use strict';
  const KEY='stoicky-kompas-data-v1';
  const INTERESTS=[
    {id:'nature',name:'Příroda',kind:'Na vzduch',title:'Jdi se na 30 minut projít',step:'Vyber místo a připrav si boty.',done:'Byl jsem se 30 minut projít.',low:true,longTitle:'Vyraz na delší výlet do přírody',longStep:'Vyber jednu trasu a zkontroluj počasí a dopravu.',longDone:'Byl jsem na delším výletě v přírodě.'},
    {id:'reading',name:'Čtení',kind:'Klid',title:'Přečti si pár stránek',step:'Polož knihu tam, kde ji zítra uvidíš.',done:'Přečetl jsem si pár stránek.',low:true},
    {id:'friends',name:'Kamarádi',kind:'Lidé',title:'Ozvi se někomu blízkému',step:'Pošli jednu zprávu bez složitého plánování.',done:'Ozval jsem se někomu blízkému.',low:true,longTitle:'Domluv si čas s kamarády',longStep:'Navrhni jeden konkrétní termín na setkání nebo výlet.',longDone:'Domluvil jsem si čas s kamarády.'},
    {id:'sport',name:'Pohyb',kind:'Pohyb',title:'Dopřej si pohyb podle energie',step:'Zvol si přiměřený pohyb a respektuj vlastní limity.',done:'Dopřál jsem si pohyb podle energie.',low:false},
    {id:'creative',name:'Tvoření',kind:'Nápad',title:'Věnuj chvíli vlastnímu projektu',step:'Otevři rozdělanou věc na 15 minut.',done:'Věnoval jsem se vlastnímu projektu.',low:false},
    {id:'rest',name:'Odpočinek',kind:'Zvolni',title:'Odpočiň si tak, jak ti to vyhovuje',step:'Hra, seriál, kniha nebo nicnedělání mohou být dobrý odpočinek.',done:'Dopřál jsem si odpočinek.',low:true},
    {id:'culture',name:'Historie a kultura',kind:'Za poznáním',title:'Zajdi na místo s příběhem',step:'Vyber muzeum, galerii nebo historickou stavbu a mrkni na otevírací dobu.',done:'Navštívil jsem kulturní nebo historické místo.',low:true,minWindow:2},
    {id:'models',name:'Modelářství',kind:'Tvoření',title:'Vrať se k rozdělanému modelu',step:'Připrav pracovní místo a vyber jeden díl, kterému se dnes chceš věnovat.',done:'Pracoval jsem na modelu.',low:true,minWindow:2},
    {id:'hike',name:'Delší výšlapy',kind:'Výlet',title:'Vyraz na pěší výlet',step:'Vyber jednu trasu přiměřenou energii a zkontroluj počasí i cestu zpátky.',done:'Vyrazil jsem na pěší výlet.',low:false,minWindow:3},
    {id:'discover',name:'Hledání v terénu',kind:'Objevování',title:'Vydej se na výpravu za drobným objevem',step:'Zvaž vhodné místo, podmínky a to, jestli na to máš dnes chuť.',done:'Vyrazil jsem na objevovací výpravu.',low:false,minWindow:3},
    {id:'travel',name:'Cestování',kind:'Plány',title:'Otevři si mapu další cesty',step:'Vyber jedno místo, které bys chtěl časem navštívit; nemusíš dnes nic kupovat.',done:'Podíval jsem se na mapu možné budoucí cesty.',low:true},
    {id:'close',name:'Blízcí',kind:'Vztahy',title:'Navrhni společný čas někomu blízkému',step:'Pošli jednoduchý návrh na procházku, kulturu nebo klidný večer.',done:'Navrhl jsem společný čas někomu blízkému.',low:true}
  ];
  const WORDS={nature:/přírod|procház|venku|výlet|\bles\b/i,reading:/čt|knih/i,friends:/kamarád|přátel|kulečník|setkán/i,sport:/běh|běž|cvič|fitk|sport/i,creative:/tvoř|projekt|kresl|psaní/i,rest:/odpoč|spán|klid/i,culture:/muze|galer|hrad|architektur|výstav/i,models:/model|lepen|stavebnic/i,hike:/trek|hike|výšlap|túra/i,discover:/zkameně|trilobit|geolog/i,travel:/cestov|dovolen|zahranič/i,close:/přítelk|partner|rodin|blízk/i};
  const $=id=>document.getElementById(id);
  const escDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const today=()=>escDate(new Date());
  const weekStart=(date=new Date())=>{const d=new Date(date.getFullYear(),date.getMonth(),date.getDate());d.setDate(d.getDate()-((d.getDay()+6)%7));return escDate(d)};
  const dateFromISO=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)};
  const dateLabel=s=>dateFromISO(s).toLocaleDateString('cs-CZ',{day:'numeric',month:'long',year:'numeric'});
  const weekLabel=s=>{const d=dateFromISO(s),end=new Date(d);end.setDate(d.getDate()+6);return `${d.toLocaleDateString('cs-CZ',{day:'numeric',month:'numeric'})}–${end.toLocaleDateString('cs-CZ',{day:'numeric',month:'numeric',year:'numeric'})}`};
  const validDate=s=>/^\d{4}-\d{2}-\d{2}$/.test(s)&&escDate(dateFromISO(s))===s;
  const cleanText=s=>String(s||'').slice(0,5000);
  const PERSONAL_INTERESTS=['culture','models','hike','discover','travel','close'];
  const fresh=()=>({version:1,entries:{},goals:[],checks:{},reflections:{},interests:['nature','reading','friends','sport','rest',...PERSONAL_INTERESTS],interestsVersion:2,suggestions:{},mentorSessions:[],rituals:{},xpEvents:{}});
  function normalize(raw){
    if(!raw||raw.version!==1||typeof raw!=='object')throw Error('Neznámý formát zálohy.');
    const data=fresh();
    for(const [date,e] of Object.entries(raw.entries||{}))if(validDate(date)&&e&&typeof e==='object')data.entries[date]={good:cleanText(e.good),learned:cleanText(e.learned),note:cleanText(e.note),activities:Array.isArray(e.activities)?e.activities.filter(id=>INTERESTS.some(x=>x.id===id)).slice(0,12):[]};
    data.goals=(Array.isArray(raw.goals)?raw.goals:[]).slice(0,100).filter(g=>g&&typeof g.name==='string'&&Number.isInteger(g.target)&&g.target>=1&&g.target<=14&&typeof g.id==='string').map(g=>({id:g.id.slice(0,80),name:g.name.slice(0,70),target:g.target}));
    for(const [id,days] of Object.entries(raw.checks||{}))if(Array.isArray(days))data.checks[id.slice(0,80)]=[...new Set(days.filter(validDate))].slice(0,3000);
    for(const [date,r] of Object.entries(raw.reflections||{}))if(validDate(date)&&r&&typeof r==='object')data.reflections[date]={good:cleanText(r.good),control:cleanText(r.control),next:cleanText(r.next)};
    if(Array.isArray(raw.interests)){data.interests=raw.interests.filter(id=>INTERESTS.some(x=>x.id===id));if(raw.interestsVersion!==2)data.interests=[...new Set([...data.interests,...PERSONAL_INTERESTS])]}
    if(raw.suggestions&&typeof raw.suggestions==='object'){for(const [id,date] of Object.entries(raw.suggestions))if(INTERESTS.some(x=>x.id===id)&&validDate(date))data.suggestions[id]=date}
    if(Array.isArray(raw.mentorSessions))data.mentorSessions=raw.mentorSessions.slice(-100).filter(s=>s&&validDate(s.date)&&typeof s.situation==='string').map(s=>({id:cleanText(s.id).slice(0,80),date:s.date,situation:cleanText(s.situation),fact:cleanText(s.fact),story:cleanText(s.story),control:cleanText(s.control),outside:cleanText(s.outside),virtue:['wisdom','justice','courage','moderation'].includes(s.virtue)?s.virtue:'wisdom',next:cleanText(s.next)}));
    for(const [date,r] of Object.entries(raw.rituals||{}))if(validDate(date)&&r&&typeof r==='object')data.rituals[date]={morning:{intention:cleanText(r.morning?.intention),obstacle:cleanText(r.morning?.obstacle)},evening:{good:cleanText(r.evening?.good),hard:cleanText(r.evening?.hard),next:cleanText(r.evening?.next)}};
    for(const [key,event] of Object.entries(raw.xpEvents||{}).slice(0,20000))if(key.length<=180&&event&&Number.isInteger(event.points)&&event.points>=1&&event.points<=20&&validDate(event.date))data.xpEvents[key]={points:event.points,date:event.date};
    return data;
  }
  let data;try{data=normalize(JSON.parse(localStorage.getItem(KEY)))}catch{data=fresh()}
  const status=message=>{$('status').textContent=message;clearTimeout(status.timer);status.timer=setTimeout(()=>$('status').textContent='',6000)};
  const save=()=>{try{syncXp();localStorage.setItem(KEY,JSON.stringify(data));renderJourney();renderWeekStrip();return true}catch{status('Uložení se nepovedlo. Stáhni si zálohu a zkontroluj volné místo v prohlížeči.');return false}};
  const node=(tag,cls,content)=>{const el=document.createElement(tag);if(cls)el.className=cls;if(content!=null)el.textContent=content;return el};
  const blank=(container,message)=>container.append(node('p','muted',message));
  function showView(id){document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.id===id));document.querySelectorAll('[data-view]').forEach(el=>{el.classList.toggle('active',el.dataset.view===id);if(el.dataset.view===id)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current')});window.scrollTo({top:0,behavior:'smooth'})}
  document.querySelectorAll('[data-view],[data-jump]').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.view||btn.dataset.jump)));
  $('today-date').textContent=new Date().toLocaleDateString('cs-CZ',{weekday:'long',day:'numeric',month:'long'});
  $('entry-date').value=today();$('entry-date').max=today();
  function renderActivityInputs(){const holder=$('activity-inputs');holder.replaceChildren();for(const interest of INTERESTS){const label=node('label','activity-choice'),box=node('input');box.type='checkbox';box.value=interest.id;box.name='activity';label.append(box,document.createTextNode(` ${interest.name}`));holder.append(label)}}
  renderActivityInputs();
  function loadEntry(){const e=data.entries[$('entry-date').value]||{};$('entry-good').value=e.good||'';$('entry-learned').value=e.learned||'';$('entry-note').value=e.note||'';document.querySelectorAll('input[name=activity]').forEach(box=>box.checked=(e.activities||[]).includes(box.value))}
  $('entry-date').addEventListener('change',loadEntry);
  $('journal-form').addEventListener('submit',event=>{event.preventDefault();const date=$('entry-date').value;if(!validDate(date)||date>today())return status('Vyber dnešní nebo dřívější den.');const entry={good:$('entry-good').value.trim(),learned:$('entry-learned').value.trim(),note:$('entry-note').value.trim(),activities:[...document.querySelectorAll('input[name=activity]:checked')].map(box=>box.value)};if(!entry.good&&!entry.learned&&!entry.note&&!entry.activities.length)return status('Napiš myšlenku nebo označ aktivitu.');data.entries[date]=entry;if(save()){status('Zápis uložen.');render()}});
  function renderEntries(){const container=$('entry-list');container.replaceChildren();const dates=Object.keys(data.entries).sort().reverse();if(!dates.length)return blank(container,'Zatím žádné zápisy.');for(const date of dates.slice(0,25)){const item=node('article','entry');item.append(node('h4','',dateLabel(date)));const e=data.entries[date];for(const [label,key] of [['Povedlo se','good'],['Naučil ses','learned'],['Poznámka','note']])if(e[key])item.append(node('p','',`${label}: ${e[key]}`));if(e.activities?.length)item.append(node('small','',`Aktivity: ${e.activities.map(id=>INTERESTS.find(x=>x.id===id)?.name).filter(Boolean).join(', ')}`));const btn=node('button','small-button','Upravit');btn.type='button';btn.addEventListener('click',()=>{$('entry-date').value=date;loadEntry();showView('journal')});item.append(btn);container.append(item)}if(dates.length>25)blank(container,`Zobrazeno posledních 25 z ${dates.length} zápisů; všechny jsou v záloze.`)}
  $('goal-form').addEventListener('submit',event=>{event.preventDefault();const name=$('goal-name').value.trim(),target=Number($('goal-target').value);if(!name||!Number.isInteger(target)||target<1||target>14)return status('Zadej název a počet 1 až 14.');data.goals.push({id:crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`,name:name.slice(0,70),target});if(save()){$('goal-form').reset();$('goal-target').value=3;render()}});
  function countWeek(id){const start=weekStart();return (data.checks[id]||[]).filter(d=>weekStart(dateFromISO(d))===start).length}
  function renderGoals(){const container=$('goal-list'),home=$('home-goals');container.replaceChildren();home.replaceChildren();$('week-label').textContent=weekLabel(weekStart());if(!data.goals.length){blank(container,'Zatím žádné cíle.');blank(home,'Zatím žádné cíle.');return}for(const goal of data.goals){const count=countWeek(goal.id),box=node('article','goal-card'),head=node('div','goal-head');head.append(node('strong','',goal.name),node('span','goal-meta',`${count} / ${goal.target} tento týden`));box.append(head);const progress=node('div','progress'),bar=node('span');bar.style.width=`${Math.min(100,100*count/goal.target)}%`;progress.append(bar);box.append(progress);const actions=node('div','goal-actions');const dayLabel=node('label','date-choice','Den: '),day=node('input');day.type='date';day.value=today();day.min=weekStart();day.max=today();day.setAttribute('aria-label',`Den pro cíl ${goal.name}`);dayLabel.append(day);actions.append(dayLabel);const add=node('button','small-button','+ Zapsat den');add.type='button';add.addEventListener('click',()=>{const date=day.value;if(!validDate(date)||date<weekStart()||date>today())return status('Vyber den v tomto týdnu.');if((data.checks[goal.id]||[]).includes(date))return status('Tenhle den už máš zapsaný.');data.checks[goal.id]=[...(data.checks[goal.id]||[]),date];if(save())render()});actions.append(add);const undo=node('button','small-button','Vrátit zvolený den');undo.type='button';undo.addEventListener('click',()=>{const date=day.value;if(!(data.checks[goal.id]||[]).includes(date))return status('Pro vybraný den není co vracet.');data.checks[goal.id]=data.checks[goal.id].filter(d=>d!==date);if(save())render()});actions.append(undo);const remove=node('button','small-button danger','Smazat cíl');remove.type='button';remove.addEventListener('click',()=>{if(!confirm(`Smazat cíl „${goal.name}“ i jeho záznamy?`))return;data.goals=data.goals.filter(g=>g.id!==goal.id);delete data.checks[goal.id];if(save())render()});actions.append(remove);box.append(actions);container.append(box);home.append(node('div','mini',`${goal.name} · ${count} z ${goal.target}`))}}
  function renderInterests(){const list=$('interest-list');list.replaceChildren();for(const interest of INTERESTS){const btn=node('button',`interest ${data.interests.includes(interest.id)?'selected':''}`,interest.name);btn.type='button';btn.setAttribute('aria-pressed',data.interests.includes(interest.id)?'true':'false');btn.addEventListener('click',()=>{data.interests=data.interests.includes(interest.id)?data.interests.filter(id=>id!==interest.id):[...data.interests,interest.id];if(save())renderInterests()});list.append(btn)}}
  let currentSuggestion=null,seen=[];
  const dayNumber=date=>{const [y,m,d]=date.split('-').map(Number);return Math.floor(Date.UTC(y,m-1,d)/86400000)};
  const daysSince=date=>dayNumber(today())-dayNumber(date);
  const hasWords=values=>values.some(value=>typeof value==='string'&&value.trim());
  const levelThreshold=level=>{const n=level-1;return 60*n+6*n*n};
  const LEVEL_NAMES=[[100,'Celoživotní praktik'],[75,'Průvodce'],[50,'Zkušený stoik'],[35,'Cvičitel úsudku'],[20,'Vytrvalý praktik'],[10,'Začínající stoik'],[5,'Učeň'],[1,'Pozorovatel']];
  function activeDates(){const dates=new Set(),mark=date=>{if(validDate(date)&&date<=today())dates.add(date)};
    for(const [date,e] of Object.entries(data.entries))if(hasWords([e.good,e.learned,e.note])||e.activities?.length)mark(date);
    for(const goal of data.goals)for(const date of data.checks[goal.id]||[])mark(date);
    for(const session of data.mentorSessions)if(session.situation.trim())mark(session.date);
    for(const [date,r] of Object.entries(data.rituals))if(hasWords([r.morning?.intention,r.morning?.obstacle,r.evening?.good,r.evening?.hard,r.evening?.next]))mark(date);
    return [...dates].sort();
  }
  function syncXp(){const events=data.xpEvents,add=(key,date,points)=>{if(date<=today()&&!Object.hasOwn(events,key)&&Object.keys(events).length<20000)events[key]={date,points}};
    for(const [date,e] of Object.entries(data.entries))if(hasWords([e.good,e.learned,e.note])||e.activities?.length)add(`journal:${date}`,date,8);
    const goalCounts={};for(const event of Object.values(events))if(event.points===7)goalCounts[event.date]=(goalCounts[event.date]||0)+1;
    for(const goal of data.goals)for(const date of [...(data.checks[goal.id]||[])].sort()){const key=`goal:${goal.id}:${date}`;if(!Object.hasOwn(events,key)&&(goalCounts[date]||0)<2&&date<=today()){add(key,date,7);goalCounts[date]=(goalCounts[date]||0)+1}}
    for(const session of data.mentorSessions)if(session.situation.trim())add(`mentor:${session.date}`,session.date,8);
    for(const [date,r] of Object.entries(data.rituals)){if(hasWords([r.morning?.intention,r.morning?.obstacle]))add(`morning:${date}`,date,2);if(hasWords([r.evening?.good,r.evening?.hard,r.evening?.next]))add(`evening:${date}`,date,3)}
    for(const [week,r] of Object.entries(data.reflections))if(hasWords([r.good,r.control,r.next]))add(`reflection:${week}`,week,12);
    const dates=activeDates();for(let i=1;i<dates.length;i++)if(dayNumber(dates[i])-dayNumber(dates[i-1])>=7)add(`return:${dates[i]}`,dates[i],10);
  }
  function renderJourney(){const total=Object.values(data.xpEvents).reduce((sum,event)=>sum+event.points,0);let level=1;while(levelThreshold(level+1)<=total)level++;const start=levelThreshold(level),end=levelThreshold(level+1),title=LEVEL_NAMES.find(([min])=>level>=min)[1];$('journey-title').textContent=`Úroveň ${level} · ${title}`;$('journey-total').textContent=`${total} XP`;$('journey-next').textContent=`Do další úrovně ${end-total} XP`;$('journey-bar').style.width=`${Math.round((total-start)/(end-start)*100)}%`;$('top-level').textContent=`Úroveň ${level}`;$('top-level').setAttribute('aria-label',`Úroveň ${level}, ${title}. Zobrazit přehled.`)}
  function renderWeekStrip(){const start=weekStart(),dates=new Set(activeDates()),now=today(),holder=$('week-days');holder.replaceChildren();$('week-glance-range').textContent=weekLabel(start);let count=0;for(let i=0;i<7;i++){const day=dateFromISO(start);day.setDate(day.getDate()+i);const date=escDate(day),logged=dates.has(date),future=date>now;if(logged)count++;const btn=node('button',`week-day${logged?' logged':''}${date===now?' today':''}`);btn.type='button';btn.disabled=future;btn.setAttribute('aria-label',`${dateLabel(date)}: ${future?'budoucí den':logged?'zaznamenaný den':'bez záznamu'}`);btn.append(node('strong','',['Po','Út','St','Čt','Pá','So','Ne'][i]),node('small','',String(day.getDate())));if(!future)btn.addEventListener('click',()=>{$('entry-date').value=date;loadEntry();showView('journal')});holder.append(btn)}$('week-glance-summary').textContent=count?`${count} ${count===1?'den':count<=4?'dny':'dní'} se záznamem`: 'Zatím žádný záznam.'}
  function relevantDates(interest){const dates=new Set();for(const [date,e] of Object.entries(data.entries)){const text=[e.good,e.learned,e.note].join(' ');if(e.activities?.includes(interest.id)||WORDS[interest.id].test(text))dates.add(date)}for(const goal of data.goals)if(WORDS[interest.id].test(goal.name))for(const date of data.checks[goal.id]||[])dates.add(date);return [...dates].filter(date=>date<=today()).sort().reverse()}
  function renderBalance(){const holder=$('balance-list');holder.replaceChildren();const logged=Object.keys(data.entries).filter(date=>date<=today()&&daysSince(date)<30).length;if(!logged)return blank(holder,'Zatím bez záznamů.');for(const interest of INTERESTS){const count=relevantDates(interest).filter(date=>daysSince(date)<30).length;const row=node('div','balance-row');row.append(node('strong','',interest.name),node('span','muted',count?`${count} ${count===1?'den':'dní'} v záznamech`:'Bez záznamu'));holder.append(row)}}
  const openingTime=new Date();$('free-window').value=[0,6].includes(openingTime.getDay())||(openingTime.getDay()===5&&openingTime.getHours()>=15)?'3':'1';
  function suggestion(){const windowSize=Number($('free-window').value)||1,energy=document.querySelector('input[name=energy]:checked')?.value||'medium';let pool=INTERESTS.filter(x=>data.interests.includes(x.id)&&(x.minWindow||1)<=windowSize&&(energy!=='low'||x.low));if(!pool.length)pool=INTERESTS.filter(x=>x.id==='rest');const history=Object.keys(data.entries).filter(date=>date<=today()&&daysSince(date)<30).length;const ranked=pool.map(x=>{const last=relevantDates(x)[0],recent=data.suggestions[x.id],score=(last?Math.min(32,daysSince(last)):history>=4?32:10)+(energy==='high'?(x.low?0:5):0)+(recent&&daysSince(recent)<7?-18:0);return {...x,last,score}}).sort((a,b)=>b.score-a.score);let pick=ranked.find(x=>!seen.includes(x.id));if(!pick){seen=[];pick=ranked[0]}seen.push(pick.id);currentSuggestion={...pick,doneText:windowSize===3&&pick.longDone?pick.longDone:pick.done};$('complete-suggestion').disabled=false;$('suggestion-kind').textContent=pick.kind;$('suggestion-title').textContent=windowSize===3&&pick.longTitle?pick.longTitle:pick.title;const gap=pick.last?daysSince(pick.last):null;$('suggestion-reason').textContent=gap!=null&&gap>=14?`V zápiscích o „${pick.name.toLowerCase()}“ není ${gap} dní zmínka.`:gap==null&&history>=4?`V zápiscích za posledních 30 dní není zmínka o „${pick.name.toLowerCase()}“.`:'Podle tvého času, energie a zájmů.';$('suggestion-step').textContent=`První krok: ${windowSize===3&&pick.longStep?pick.longStep:pick.step}`;$('suggestion-feedback').textContent='';$('edit-completion').hidden=true;$('suggestion-card').hidden=false}
  $('suggest-button').addEventListener('click',suggestion);$('another-suggestion').addEventListener('click',suggestion);$('accept-suggestion').addEventListener('click',()=>{if(!currentSuggestion)return;data.suggestions[currentSuggestion.id]=today();if(save())$('suggestion-feedback').textContent='Nápad uložen jako plán.'});
  $('complete-suggestion').addEventListener('click',()=>{
    if(!currentSuggestion||$('complete-suggestion').disabled)return;
    const date=today(),entry=data.entries[date]||{good:'',learned:'',note:'',activities:[]},done=currentSuggestion.doneText;
    if(entry.good.split('\n').includes(done))return status('Tuhle aktivitu už máš dnes v deníku zapsanou.');
    const updated=[entry.good,done].filter(Boolean).join('\n');if(updated.length>5000)return status('Zápis už je dlouhý. Otevři deník a doplň aktivitu tam.');
    const inputs=['good','learned','note'].every(key=>$(`entry-${key}`).value===(entry[key]||''));
    const selected=[...document.querySelectorAll('input[name=activity]:checked')].map(box=>box.value);
    const safeReload=$('entry-date').value===date&&inputs&&selected.length===(entry.activities||[]).length&&selected.every(id=>entry.activities.includes(id));
    data.entries[date]={good:updated,learned:entry.learned||'',note:entry.note||'',activities:[...new Set([...(entry.activities||[]),currentSuggestion.id])]};
    if(save()){if(safeReload)loadEntry();render();$('complete-suggestion').disabled=true;$('edit-completion').hidden=false;$('suggestion-feedback').textContent='Zapsáno do deníku. Text můžeš upravit.'}
  });
  $('edit-completion').addEventListener('click',()=>{$('entry-date').value=today();loadEntry();showView('journal')});
  function renderThought(){const items=window.STOIC_THOUGHTS||[];if(!items.length)return;const thought=items[((dayNumber(today())%items.length)+items.length)%items.length],section=Number(thought.section.match(/\d+/)?.[0]);$('thought-source').textContent=thought.type==='stoic'?`Epiktétos, Enchiridion ${thought.section}`:`Buddhistický text ${thought.section}`;$('thought-count').textContent=thought.type==='stoic'&&window.FAVORITE_SECTIONS.includes(section)?'★ Tvoje vybraná kapitola':'';$('thought-title').textContent=thought.title;$('thought-text').textContent=thought.thought;$('thought-question').textContent=thought.question;$('thought-step').textContent=`Krok: ${thought.step}`}
  $('thought-archive').addEventListener('toggle',()=>{const holder=$('thought-library');if(!$('thought-archive').open||holder.children.length)return;for(const card of window.STOIC_LIBRARY||[]){const section=Number(card.section.match(/\d+/)?.[0]),favorite=card.type==='stoic'&&window.FAVORITE_SECTIONS.includes(section),item=node('article','thought-item');item.append(node('small','kicker',card.type==='stoic'?`ENCHIRIDION ${card.section}${favorite?' · ★ TVŮJ VÝBĚR':''}`:`BUDDHISMUS · ${card.section}`),node('h3','',card.title),node('p','',card.thought),node('p','muted',`Otázka: ${card.question}`),node('p','muted',`Krok: ${card.step}`));if(card.sourceUrl){const link=node('a','source','Zobrazit pramen ↗');link.href=card.sourceUrl;link.target='_blank';link.rel='noopener noreferrer';item.append(link)}holder.append(item)}});
  function renderHomePrompt(){const day=new Date().getDay(),freeDay=day===0||day===5||day===6,history=Object.keys(data.entries).filter(date=>date<=today()&&daysSince(date)<30).length,lastFriends=relevantDates(INTERESTS.find(x=>x.id==='friends'))[0],friendGap=lastFriends?daysSince(lastFriends):null;if(freeDay){$('home-prompt-title').textContent='Jak chceš využít delší volno?';$('home-prompt').textContent='Výlet, setkání, tvoření nebo odpočinek? Kompas nabídne nápad podle tvého času.'}else if(data.interests.includes('friends')&&history>=4&&(friendGap==null||friendGap>=21)){$('home-prompt-title').textContent='Co vztahy v poslední době?';$('home-prompt').textContent='V zápiscích je málo zmínek o setkání s blízkými. Kompas může nabídnout nápad.'}else{$('home-prompt-title').textContent='Co dnes potřebuješ?';$('home-prompt').textContent='Vyber si nápad podle času a energie.'}}
  const VIRTUES={wisdom:{name:'Moudrost',prompt:'Než se rozhodneš, zkus znovu oddělit to, co víš, od toho, co si domýšlíš.'},justice:{name:'Spravedlnost',prompt:'Zvaž, co je fér k druhým i k tobě. Tvoje hranice mají také místo.'},courage:{name:'Odvaha',prompt:'Odvaha neznamená nemít strach. Jde o přiměřený krok navzdory obavě.'},moderation:{name:'Uměřenost',prompt:'Hledej míru, která je dnes udržitelná. Odpočinek může být rozumná volba.'}};
  let mentorStage=0;
  function showMentorStage(stage){mentorStage=Math.max(0,Math.min(3,stage));document.querySelectorAll('.mentor-stage').forEach(el=>el.hidden=Number(el.dataset.stage)!==mentorStage);$('mentor-progress').textContent=`KROK ${mentorStage+1} ZE 4`;const messages=['Pojďme se na to podívat bez známkování. Co se právě děje?','Díky, že ses u toho zastavil. Nejdřív zkusíme oddělit událost od závěru, který se nabízí.',$('mentor-story').value.trim()?'Výklad jsi pojmenoval. Teď hledej svůj díl vlivu, ne odpovědnost za všechno.':'Zkus se podívat, co můžeš udělat ty. Ostatní můžeš na chvíli pustit.',$('mentor-control').value.trim()?'Máš pojmenované něco, co můžeš ovlivnit. Jak při tom chceš jednat?':'Někdy je jediný možný krok odpočinek nebo čas. I to je platná volba.'];$('mentor-message').textContent=messages[mentorStage]}
  document.querySelectorAll('.mentor-next').forEach(btn=>btn.addEventListener('click',()=>{if(mentorStage===0&&!$('mentor-situation').value.trim())return status('Napiš pár slov o situaci, kterou chceš probrat.');if(mentorStage===0)$('mentor-result').hidden=true;showMentorStage(mentorStage+1)}));
  document.querySelectorAll('.mentor-back').forEach(btn=>btn.addEventListener('click',()=>showMentorStage(mentorStage-1)));
  $('mentor-virtue').addEventListener('change',()=>{$('mentor-virtue-hint').textContent=VIRTUES[$('mentor-virtue').value].prompt});
  $('mentor-virtue-hint').textContent=VIRTUES.wisdom.prompt;
  function renderMentorResult(session){const holder=$('mentor-result');holder.replaceChildren();holder.append(node('h3','','Co si z rozhovoru odnášíš'));if(session.fact)holder.append(node('p','',`Jisté je: ${session.fact}`));if(session.story)holder.append(node('p','',`Tvůj výklad, který můžeš znovu přezkoumat: ${session.story}`));if(session.control)holder.append(node('p','',`Ve tvých silách: ${session.control}`));if(session.outside)holder.append(node('p','',`Co teď můžeš pustit: ${session.outside}`));holder.append(node('p','',`${VIRTUES[session.virtue].name}: ${VIRTUES[session.virtue].prompt}`));holder.append(node('div','first-step',session.next?`Tvůj příští krok: ${session.next}`:'Další krok můžeš zvolit až ve chvíli, kdy na něj budeš mít prostor.'));holder.hidden=false}
  $('mentor-form').addEventListener('submit',event=>{event.preventDefault();const session={id:crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`,date:today(),situation:$('mentor-situation').value.trim(),fact:$('mentor-fact').value.trim(),story:$('mentor-story').value.trim(),control:$('mentor-control').value.trim(),outside:$('mentor-outside').value.trim(),virtue:$('mentor-virtue').value,next:$('mentor-next-step').value.trim()};if(!session.situation)return status('Napiš nejdřív situaci, kterou chceš probrat.');data.mentorSessions.push(session);data.mentorSessions=data.mentorSessions.slice(-100);if(save()){renderMentorResult(session);renderMentorHistory();$('mentor-form').reset();$('mentor-virtue-hint').textContent=VIRTUES.wisdom.prompt;showMentorStage(0);status('Rozhovor uložen.')}});
  function renderMentorHistory(){const holder=$('mentor-history');holder.replaceChildren();if(!data.mentorSessions.length)return blank(holder,'Zatím žádný rozhovor.');for(const session of [...data.mentorSessions].reverse().slice(0,10)){const item=node('article','entry');item.append(node('small','muted',dateLabel(session.date)),node('h4','',session.situation));if(session.next)item.append(node('p','',`Další krok: ${session.next}`));const open=node('button','small-button','Zobrazit shrnutí');open.type='button';open.addEventListener('click',()=>{renderMentorResult(session);window.scrollTo({top:0,behavior:'smooth'})});const remove=node('button','small-button danger','Smazat');remove.type='button';remove.addEventListener('click',()=>{if(!confirm('Smazat tento rozhovor?'))return;data.mentorSessions=data.mentorSessions.filter(s=>s.id!==session.id);if(save()){renderMentorHistory();$('mentor-result').hidden=true}});item.append(open,document.createTextNode(' '),remove);holder.append(item)}}
  function loadRituals(){const r=data.rituals[today()]||{},morning=r.morning||{},evening=r.evening||{};$('morning-intention').value=morning.intention||'';$('morning-obstacle').value=morning.obstacle||'';$('evening-good').value=evening.good||'';$('evening-hard').value=evening.hard||'';$('evening-next').value=evening.next||''}
  $('morning-form').addEventListener('submit',event=>{event.preventDefault();const morning={intention:$('morning-intention').value.trim(),obstacle:$('morning-obstacle').value.trim()};if(!morning.intention&&!morning.obstacle)return status('Ranní úvaha může počkat. Napiš něco, až budeš chtít.');data.rituals[today()]={...(data.rituals[today()]||{}),morning};if(save()){renderHomeMentor();status('Ranní úvaha uložena.')}});
  $('evening-form').addEventListener('submit',event=>{event.preventDefault();const evening={good:$('evening-good').value.trim(),hard:$('evening-hard').value.trim(),next:$('evening-next').value.trim()};if(!evening.good&&!evening.hard&&!evening.next)return status('Nemusíš nic vyplňovat. Večerní ohlédnutí je dobrovolné.');data.rituals[today()]={...(data.rituals[today()]||{}),evening};if(save())status('Ohlédnutí uloženo.')});
  function renderHomeMentor(){const morning=data.rituals[today()]?.morning;$('mentor-teaser-text').textContent=morning?.intention?`Dnešní záměr: ${morning.intention}`:'Ujasni si situaci ve čtyřech krocích.'}
  function loadReflection(){const r=data.reflections[weekStart()]||{};$('reflection-week').textContent=`Týden ${weekLabel(weekStart())}`;$('reflect-good').value=r.good||'';$('reflect-control').value=r.control||'';$('reflect-next').value=r.next||''}
  $('reflection-form').addEventListener('submit',event=>{event.preventDefault();const r={good:$('reflect-good').value.trim(),control:$('reflect-control').value.trim(),next:$('reflect-next').value.trim()};if(!Object.values(r).some(Boolean))return status('Stačí jedna věta, ale napiš ji před uložením.');data.reflections[weekStart()]=r;if(save()){status('Ohlédnutí uloženo.');renderReflections()}});
  function renderReflections(){const container=$('reflection-list');container.replaceChildren();const weeks=Object.keys(data.reflections).sort().reverse();if(!weeks.length)return blank(container,'Zatím žádné ohlédnutí.');for(const week of weeks.slice(0,15)){const r=data.reflections[week],item=node('article','reflection-item');item.append(node('h4','',weekLabel(week)));for(const [label,key] of [['Povedlo se','good'],['V mých silách','control'],['Další krok','next']])if(r[key])item.append(node('p','',`${label}: ${r[key]}`));container.append(item)}}
  function render(){renderEntries();renderGoals();renderInterests();renderReflections();renderBalance();renderThought();renderHomePrompt();renderMentorHistory();renderHomeMentor();renderJourney();renderWeekStrip()}
  $('export-button').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`stoicky-kompas-zaloha-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Záloha se stahuje.')});
  $('import-file').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;try{if(file.size>5_000_000)throw Error('Soubor je příliš velký.');const next=normalize(JSON.parse(await file.text()));if(!confirm('Načtení zálohy nahradí současné záznamy v tomto prohlížeči. Pokračovat?'))return;data=next;if(save()){loadEntry();loadReflection();loadRituals();$('mentor-result').hidden=true;render();status('Záloha načtena.')}}catch(err){status(`Zálohu se nepovedlo načíst: ${err.message}`)}finally{event.target.value=''}});
  loadEntry();loadReflection();loadRituals();save();render();
  if('serviceWorker'in navigator&&location.protocol!=='file:')window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();
