// České autorské parafráze a otázky podle přiloženého Enchiridionu a čtenářských poznámek.
// Nejde o doslovné citáty ani o úplný překlad knihy.
window.STOIC_THOUGHTS = [
  {type:'stoic',section:'§ 1',title:'Co je v mých silách',thought:'Můžeš rozhodovat o svém úsudku a další volbě. Výsledek ani mínění druhých plně neřídíš.',question:'Která část dnešní situace je opravdu na tobě?',step:'Pojmenuj jeden krok, který můžeš udělat.'},
  {type:'stoic',section:'§ 2',title:'Přání a zklamání',thought:'Když zavěsíš svůj klid na věc mimo svůj vliv, předáš jí nad sebou moc.',question:'Čeho se teď držíš tak pevně, až tě to svazuje?',step:'Zkus přání převést na čin, který ovlivníš.'},
  {type:'stoic',section:'§ 3',title:'Vážím si toho, co mám',thought:'Věci i chvíle s lidmi jsou cenné právě proto, že nejsou samozřejmé.',question:'Čeho si dnes můžeš všimnout s větší vděčností?',step:'Věnuj tomu minutu opravdové pozornosti.'},
  {type:'stoic',section:'§ 4',title:'Předvídej bez strachu',thought:'Do plánů patří i drobné překážky. Když přijdou, nemusí ti vzít směr.',question:'Co se může pokazit a jak chceš reagovat?',step:'Připrav si klidnou variantu plánu.'},
  {type:'stoic',section:'§ 5',title:'Událost a její výklad',thought:'Mezi tím, co se stalo, a tvým závěrem o tom je prostor k zamyšlení.',question:'Co víš jistě a co si jen domýšlíš?',step:'Zkus stejnou událost popsat bez hodnocení.'},
  {type:'stoic',section:'§ 6',title:'Radost z vlastního jednání',thought:'Radost z věcí je v pořádku. Pevnější oporu ale můžeš najít v tom, jak jednáš.',question:'Na jaké své dnešní rozhodnutí můžeš být hrdý?',step:'Připomeň si konkrétní čin, nikoli výsledek.'},
  {type:'stoic',section:'§ 8',title:'Přijmout skutečnost',thought:'Přijmout, co se děje, neznamená vzdát se jednání. Je to začátek poctivé reakce.',question:'S čím teď zbytečně zápasíš jen proto, že už se to stalo?',step:'Odliš fakt od dalšího kroku.'},
  {type:'stoic',section:'§ 9',title:'Nemoc není selhání',thought:'Tělo může potřebovat klid a péči. Tvá hodnota se tím nemění.',question:'Jaký rozumný krok odpovídá tvým dnešním možnostem?',step:'Uprav plán podle skutečné kapacity.'},
  {type:'stoic',section:'§ 10',title:'Příležitost procvičit charakter',thought:'Nepříjemná situace může být příležitostí k trpělivosti nebo odvaze, aniž bys ji musel vítat.',question:'Jakou vlastnost chceš v této situaci použít?',step:'Zvol jednu drobnou odpověď místo automatické reakce.'},
  {type:'mindfulness',section:'Všímavost',title:'Vrať se k přítomnosti',thought:'Na chvíli si všimni dechu, těla a okolí. Nic nemusíš opravovat.',question:'Co právě cítíš, aniž bys to hned hodnotil?',step:'Zastav se na tři klidné nádechy.'},
  {type:'stoic',section:'§ 12',title:'Cena za klid',thought:'Některé drobné nepříjemnosti stojí méně než energie, kterou by tě stál boj s nimi.',question:'Která maličkost dnes nestojí za tvůj vnitřní spor?',step:'Pusť ji, pokud je to bezpečné a rozumné.'},
  {type:'stoic',section:'§ 14',title:'Vlastní směr',thought:'Svoboda roste, když se tvé rozhodování neopírá jen o to, co chtějí ostatní.',question:'Kde se teď rozhoduješ hlavně kvůli cizímu uznání?',step:'Vrať se ke svému důvodu.'},
  {type:'stoic',section:'§ 17',title:'Hraj své karty dobře',thought:'Okolnosti sis vždy nevybral. Způsob, jak v nich jednáš, však můžeš utvářet.',question:'Jak by vypadal dobrý tah s kartami, které máš?',step:'Udělej jeden proveditelný tah.'},
  {type:'stoic',section:'§ 19',title:'Srovnávej se s vlastním úsilím',thought:'Cizí výsledky nemusejí být měřítkem tvé hodnoty. Všimni si svého poctivého postupu.',question:'V čem ses oproti sobě posunul?',step:'Zapiš malý pokrok bez srovnávání s druhými.'},
  {type:'stoic',section:'§ 20',title:'Mezera před reakcí',thought:'Když tě někdo rozčílí, můžeš si dát chvíli na posouzení, co se opravdu stalo.',question:'Jaký úsudek právě zesiluje tvůj hněv?',step:'Než odpovíš, dej si jednu pauzu.'},
  {type:'stoic',section:'§ 22',title:'Nenech se odradit posměchem',thought:'Když se pokoušíš žít podle svých zásad, někdo to nemusí chápat. Důvod ke změně hledej v argumentech, ne v posměchu.',question:'Za kterou rozumnou volbou si chceš stát?',step:'Připomeň si, proč ti na ní záleží.'},
  {type:'stoic',section:'§ 25',title:'Každá volba má cenu',thought:'Když ti někdo předběhne cestu za cenu, kterou platit nechceš, nemusíš mu závidět.',question:'Jakou cenu za svůj cíl jsi ochotný přijmout?',step:'Pojmenuj svou hranici dřív, než budeš jednat.'},
  {type:'stoic',section:'§ 26',title:'Buď k sobě lidský',thought:'Radu, kterou umíš laskavě dát druhému, můžeš nabídnout i sobě. Smutek nepotřebuje stopky.',question:'Co bys řekl příteli ve stejné situaci?',step:'Zkus to bez výčitek říct i sobě.'},
  {type:'stoic',section:'§ 29',title:'Než se pustíš do cíle',thought:'Počáteční nadšení je příjemné, ale dobrý závazek počítá i s námahou a odpočinkem.',question:'Co tento cíl skutečně vyžaduje?',step:'Zvol tempo, které můžeš udržet.'},
  {type:'mindfulness',section:'Všímavost',title:'Myšlenka je jen myšlenka',thought:'Všimni si své myšlenky jako události v mysli. Nemusíš jí hned věřit ani s ní bojovat.',question:'Jak bys tu myšlenku pojmenoval?',step:'Řekni si: „Právě mě napadá, že…“'},
  {type:'stoic',section:'§ 30',title:'Spravedlnost ve vztazích',thought:'Chování druhých není vždy v tvých rukou. Vlastní slušnost a hranice ano.',question:'Jak chceš jednat s člověkem, se kterým je to těžké?',step:'Vyber jednu férovou odpověď, která ctí i tvé hranice.'},
  {type:'stoic',section:'§ 33',title:'Čím se obklopuješ',thought:'Tvé prostředí a společnost ovlivňují návyky. Vztahy si zaslouží vědomou péči.',question:'S kým bys chtěl být častěji v kontaktu?',step:'Pošli jednu jednoduchou zprávu.'},
  {type:'stoic',section:'§ 34',title:'Než sáhneš po rychlé úlevě',thought:'Potěšení může být dobré. Zvaž ale i to, jak se budeš cítit potom.',question:'Co ti dnešní volba přinese teď a zítra?',step:'Dej si krátkou pauzu a rozhodni se vědomě.'},
  {type:'stoic',section:'§ 37',title:'Nepřeceňuj své možnosti',thought:'Nemusíš si naložit víc, než uneseš. Pokora k vlastním možnostem je rozumná.',question:'Kde by ti pomohlo ubrat?',step:'Uprav jeden plán na uskutečnitelnou podobu.'},
  {type:'stoic',section:'§ 41',title:'Tělo a mysl',thought:'Péče o tělo je dobrá, ale výkon tě nedefinuje. Udělej místo i pro klid a úsudek.',question:'Co dnes potřebuje tělo a co mysl?',step:'Vyber jeden laskavý krok pro obojí.'},
  {type:'stoic',section:'§ 42',title:'Druhý má svůj pohled',thought:'Nemusíš souhlasit s chováním druhého, abys zkusil pochopit, z čeho vychází.',question:'Jaký jiný výklad situace je možný?',step:'Zeptej se dřív, než si uděláš závěr.'},
  {type:'stoic',section:'§ 45',title:'Popis před soudem',thought:'To, co jsi viděl, a to, co z toho vyvozuješ, nejsou vždy totéž.',question:'Co se skutečně stalo bez domněnek?',step:'Odděl pozorování od svého příběhu o něm.'},
  {type:'stoic',section:'§ 46',title:'Nech mluvit činy',thought:'Zásady se ukazují v obyčejných rozhodnutích, ne v tom, jak hezky je umíš popsat.',question:'Jakou svou hodnotu dnes převedeš do činu?',step:'Zkus drobný čin bez potřeby se jím chlubit.'},
  {type:'stoic',section:'§ 49',title:'Čtení není celý život',thought:'Číst o dobrém životě nestačí. I malý praktický pokus je součástí filozofie.',question:'Kterou myšlenku dnes opravdu vyzkoušíš?',step:'Vyber jeden čin na dnešek.'},
  {type:'mindfulness',section:'Všímavost',title:'Chvilka bez výkonu',thought:'Odpočinek nemusí být odměnou za splněný seznam. Může být součástí dobrého dne.',question:'Co by ti teď pomohlo trochu zpomalit?',step:'Dopřej si pět minut bez dalšího úkolu.'},
  {type:'stoic',section:'§ 7',title:'Vracej se k tomu podstatnému',thought:'Užívej si věcí kolem sebe, ale pamatuj, kam chceš směřovat. Radost a vědomí pomíjivosti se nevylučují.',question:'Co má dnes tvou pozornost a co je pro tebe nejdůležitější?',step:'Udělej prostor pro jednu podstatnou věc.'},
  {type:'stoic',section:'§ 11',title:'Co ti bylo dáno na čas',thought:'Ztráta bolí. Myšlenka, že nic nevlastníme navždy, může prohloubit vděčnost; nemusí ti zakazovat truchlit.',question:'Za co jsi vděčný, i když to není trvalé?',step:'Dopřej si chvíli vděčnosti nebo smutku bez souzení.'},
  {type:'stoic',section:'§ 13',title:'Charakter před dojmem',thought:'Nemusíš si vybírat mezi svými zásadami a obrazem, který o tobě mají druzí, pokaždé ve prospěch dojmu.',question:'Co bys zvolil, kdybys nemusel nikoho ohromit?',step:'Zkus se rozhodnout podle své hodnoty.'},
  {type:'stoic',section:'§ 15',title:'Na některé věci se čeká',thought:'Ne všechno přijde právě tehdy, kdy chceš. Trpělivost může být aktivní volba, ne pasivní rezignace.',question:'Kde by ti prospělo ubrat naléhavost?',step:'Udělej svůj díl a nech výsledku čas.'},
  {type:'stoic',section:'§ 16',title:'Soucit bez přebírání',thought:'Můžeš být člověku nablízku v bolesti, aniž bys tvrdil, že přesně víš, co cítí, nebo mu přikazoval klid.',question:'Kdo teď potřebuje spíš tvoji přítomnost než radu?',step:'Nabídni naslouchání.'},
  {type:'stoic',section:'§ 18',title:'Znamení a reakce',thought:'Ani nepříznivou zprávu nemusíš brát jako hotový soud o svém životě. Vliv máš na to, jak odpovíš.',question:'Co se dnes jeví hrozivě, ale ještě nemá jasný význam?',step:'Odlož předčasný závěr.'},
  {type:'stoic',section:'§ 21',title:'Připomínka konečnosti',thought:'Vědomí, že čas není neomezený, nemusí děsit. Může ti pomoct nepřikládat banalitám příliš velkou váhu.',question:'Čemu chceš věnovat omezený čas opravdu?',step:'Vyber jednu důležitou věc pro dnešek.'},
  {type:'stoic',section:'§ 24',title:'Jaká je tvoje pomoc',thought:'Užitečnost člověka se neměří jen penězi nebo postavením. Můžeš přispět i charakterem, časem a péčí.',question:'Jak můžeš být dnes druhému prospěšný ve svých možnostech?',step:'Nabídni konkrétní drobnou pomoc.'},
  {type:'stoic',section:'§ 27',title:'Chyba není identita',thought:'Nesprávný úsudek nebo čin lze napravit. Jeden omyl nemusí definovat celého člověka.',question:'Co ses z poslední chyby naučil?',step:'Zvol opravu místo nálepky.'},
  {type:'stoic',section:'§ 28',title:'Nesvěřuj svůj klid náhodě',thought:'Nemusíš každou provokaci proměnit ve vnitřní bouři. Hranice můžeš držet i klidným hlasem.',question:'Na co dnes nemusíš reagovat okamžitě?',step:'Dej si prostor před odpovědí.'},
  {type:'stoic',section:'§ 31',title:'Spravedlnost v tvých rukou',thought:'Starý text mluví o bozích. Praktická otázka pro dnešek zní: jednáš fér, i když neřídíš výsledek?',question:'Kde můžeš udělat spravedlivý krok bez záruky odměny?',step:'Rozhodni se podle svého jednání, ne podle zásluh světa.'},
  {type:'stoic',section:'§ 32',title:'Nejistá budoucnost',thought:'Předpověď ti nevezme nejistotu. Podstatné je připravit se jednat rozumně za různých okolností.',question:'Co můžeš připravit, aniž bys znal výsledek?',step:'Vytvoř jednoduchý plán A a plán B.'},
  {type:'stoic',section:'§ 35',title:'Stůj za správným činem',thought:'Když už ses po rozvaze rozhodl dobře, nenech se zpětně vláčet každým cizím pohledem.',question:'Za jaký čin by ses nemusel stydět, i kdyby vzbudil pozornost?',step:'Opři se o důvod svého rozhodnutí.'},
  {type:'stoic',section:'§ 36',title:'Zvaž i druhou stranu',thought:'To, co je výhodné pro tebe, může mít jinou cenu pro druhého. Rozum zahrnuje i ohled.',question:'Čí pohled ti v rozhodování chybí?',step:'Zkus si ho poctivě představit.'},
  {type:'stoic',section:'§ 40',title:'Důstojnost před dojmem',thought:'Dobový text hodnotí lidi způsobem, který dnes nemusíme přebírat. Použitelná otázka je, zda druhé i sebe vidíš jako osoby, ne jako ozdobu.',question:'Posuzuješ někoho podle vzhledu místo charakteru?',step:'Vrať pozornost k jeho jednání a důstojnosti.'},
  {type:'stoic',section:'§ 44',title:'Co člověka určuje',thought:'Majetek ani schopnosti koně nevypovídají o povaze jeho majitele. Stejně tak tvoje věci nejsou tvůj charakter.',question:'Jakou vlastnost chceš pěstovat bez ohledu na výbavu?',step:'Pojmenuj jeden čin, který ji ukáže.'},
  {type:'stoic',section:'§ 48',title:'Hledej začátek u sebe',thought:'U vlastního jednání má smysl začít otázkou, co můžeš změnit ty. Neznamená to nést vinu za všechno, co se stane.',question:'Co je tvá odpovědnost a co už není?',step:'Vyber svůj díl, cizí díl nech druhému.'},
  {type:'stoic',section:'§ 23',title:'Dobrý život pro sebe',thought:'Ctnost nepotřebuje publikum. Tvoje vlastní svědomí je důležitější než potlesk.',question:'Co uděláš správně, i když to nikdo neuvidí?',step:'Udělej jeden tichý dobrý čin.'},
  {type:'stoic',section:'§ 38',title:'Pozor na vlastní pozornost',thought:'Jako chráníš tělo před zraněním, můžeš chránit i svou pozornost před zbytečným rozrušením.',question:'Čemu dnes věnuješ víc prostoru, než si zaslouží?',step:'Vrať pozornost k věci, kterou ovlivníš.'},
  {type:'stoic',section:'§ 39',title:'Míra stačí',thought:'Dostatek je často klidnější než honba za stále větším pohodlím a uznáním.',question:'Kde už máš dost, i když by šlo chtít víc?',step:'Dnes u jedné věci zkus přiměřenost.'},
  {type:'stoic',section:'§ 43',title:'Dvě strany jedné situace',thought:'Na každou událost se dá podívat více způsoby. Zkus ten, který ti umožní jednat lépe.',question:'Jaký druhý pohled ti teď uniká?',step:'Popiš si obě strany bez spěchu.'},
  {type:'stoic',section:'§ 47',title:'Tichá střídmost',thought:'Když se ti podaří žít střídmě nebo lépe, nemusíš z toho dělat představení.',question:'Co ti prospívá, i když se tím nechlubíš?',step:'Pokračuj kvůli sobě.'},
  {type:'stoic',section:'§ 50',title:'Odklad není plán',thought:'Chceš-li žít podle zásad, nezačne to jednou v ideálním týdnu. Začíná to malou volbou dnes.',question:'Jakou hodnotu dnes nechceš odložit?',step:'Převeď ji do jednoduchého činu.'},
  {type:'stoic',section:'§ 51',title:'Praktikuj, co víš',thought:'Filozofie získává váhu až v praxi. Nečekej na dokonalé pochopení před prvním krokem.',question:'Které poučení už můžeš zkusit žít?',step:'Zkus ho dnes v jedné obyčejné situaci.'},
  {type:'mindfulness',section:'Všímavost',title:'Naslouchej okamžiku',thought:'Na chvíli nech stranou, co má být dál. Všimni si zvuků kolem sebe.',question:'Jaké tři zvuky právě slyšíš?',step:'Věnuj poslechu půl minuty.'},
  {type:'mindfulness',section:'Všímavost',title:'Jemné pojmenování',thought:'Pocit můžeš pojmenovat, aniž by ses za něj trestal.',question:'Jak bys teď jednoduše nazval svou náladu?',step:'Řekni si její jméno a nech ji chvíli být.'},
  {type:'mindfulness',section:'Všímavost',title:'Vědomé setkání',thought:'Krátká chvíle plné pozornosti s člověkem někdy znamená víc než dlouhý rozhovor napůl.',question:'Komu chceš dnes opravdu naslouchat?',step:'Odlož při rozhovoru telefon.'},
  {type:'mindfulness',section:'Všímavost',title:'Všimni si těla',thought:'Tělo ti někdy připomene únavu dřív než seznam úkolů. Všimnout si jí je dobrý začátek.',question:'Kde v těle teď cítíš napětí nebo uvolnění?',step:'Na chvíli se protáhni nebo si odpočiň.'},
  {type:'mindfulness',section:'Všímavost',title:'Jedna věc najednou',thought:'Nemusíš najednou řešit všechno, co ti běží hlavou. Teď můžeš být u jedné věci.',question:'Čemu věnuješ příštích pár minut pozornost?',step:'Odlož jednu rušivou věc stranou.'}
];
// Všech 51 oddílů je v knihovně právě jednou. Vybrané kapitoly se častěji vracejí v denním cyklu.
window.FAVORITE_SECTIONS=[1,2,3,5,7,8,11,14,15,18,25,33,34,42,43,45,46];
const stoicCards=window.STOIC_THOUGHTS.filter(card=>card.type==='stoic').sort((a,b)=>Number(a.section.match(/\d+/)[0])-Number(b.section.match(/\d+/)[0]));
const mindfulCards=window.STOIC_THOUGHTS.filter(card=>card.type==='mindfulness');
window.STOIC_LIBRARY=[...stoicCards,...mindfulCards];
const dailyCycle=[],firstMindful=mindfulCards.slice(0,6),favoriteCards=stoicCards.filter(card=>window.FAVORITE_SECTIONS.includes(Number(card.section.match(/\d+/)[0])));
stoicCards.forEach((card,index)=>{dailyCycle.push(card);if([8,17,25,34,42,50].includes(index))dailyCycle.push(firstMindful.shift())});
const weighted=[];let favoriteIndex=0;
dailyCycle.forEach((card,index)=>{weighted.push(card);if(index%3===2&&favoriteIndex<favoriteCards.length)weighted.push(favoriteCards[favoriteIndex++]);if(index===19)weighted.push(mindfulCards[6]);if(index===39)weighted.push(mindfulCards[7])});
window.STOIC_THOUGHTS=weighted;
